
services:
  - type: web
    name: danceplanet-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 4000
